### PR TITLE
fixed dct on mfcc

### LINKED ISSUE #107: Add new MFCC extractor
Nevo wanted to make some changes to the MFCC extractor. This will be v3.0.2.

### PR DESCRIPTION
**Pull request by nevosegal**
Also updated version to 3.0.2

Fixes #107

### CODE REVIEW

File: dist/node/extractors/mfcc.js [hunk 1]
```diff
@@ -28,37 +28,13 @@ exports.default = function (args) {
 			loggedMelBands[i] += filtered[i][j];
 		}
 
-		//log each coefficient
-		loggedMelBands[i] = Math.log(loggedMelBands[i]);
+		//log each coefficient unless it's 0.
+		loggedMelBands[i] = loggedMelBands[i] > 0.00001 ? Math.log(loggedMelBands[i]) : 0;
```
Comment (hughrawlinson) [inline dist/node/extractors/mfcc.js]: Where'd you get 0.00001? Is that from another implementation?

File: dist/node/meyda-wa.js [hunk 2]
```diff
@@ -45,11 +45,13 @@ var MeydaAnalyzer = function () {
 		self.barkScale = utilities.createBarkScale(self.bufferSize, self.sampleRate, self.bufferSize);
 		self.melFilterBank = utilities.createMelFilterBank(self.melBands, self.sampleRate, self.bufferSize);
 
+		self.inputData = null;
+
 		self.spn.onaudioprocess = function (e) {
 			// self is to obtain the current frame pcm data
-			var inputData = e.inputBuffer.getChannelData(0);
+			self.inputData = e.inputBuffer.getChannelData(0);
```
Comment (hughrawlinson) [inline dist/node/meyda-wa.js]: I'm sure I did this yesterday. Maybe it was part of my enabling buffer comparisons which hasn't been merged yet...

File: dist/node/extractors/mfcc.js (hunk 1 above)
Comment (nevosegal) [inline dist/node/extractors/mfcc.js]: I got it from Maximilian. Not sure it's the cleanest, but it solves some of the issues.

Comment (jakubfiala) [inline dist/node/extractors/mfcc.js]: Lol, that's so Maximilian-y. Almost like using ints for true/false. But here it might be so that really really small values don't make a mess in the filterbank.

Comment (hughrawlinson) [inline dist/node/extractors/mfcc.js]: Should probably add a TODO comment to come back and see how it's done elsewhere, but it's fine for now.

**Comment by nevosegal** [comment]
Commit 6f84d4e is a not very efficient fix to the fact that the node v0.12 doesn't support `.map()` and `.reduce()` on `Float32Array`.

**Comment by hughrawlinson** [comment]
Haha ok

:+1:

**Comment by jakubfiala** [comment]
:+1:
